### ISSUE TITLE
Functional and component specification feedback

### ISSUE THREAD

**Issue by elmisback** [CSE583-Group7/transit_vis#2]
* Functional
    * https://github.com/CSE583-Group7/transit_vis/blob/main/docs/functional_specification.md
    * Problem being addressed
        * Understanding what communities are most impacted by transit delays
    * Data sources, data structure
        * OneBusAway API + Socioeconomic census data
    * Users: domain, skills, programming experience
        * Transit professionals with domain knowledge but not programming experience
        * Community members without domain knowledge or programming experience
    * At least 2 use cases
        * "I want to see how transit speeds through a certain corridor compare to historical levels"
        * "I want to see typical transit speeds in different neighborhoods to help with choosing a home"
* Component
    * https://github.com/CSE583-Group7/transit_vis/blob/main/docs/component_specification.md
    * 3+ software components: what it does, inputs it requires, and outputs it provides.
        * Very clear!
        * Backend EC2 Server
        * Backend Databases
        * Folium Interface
            * Interactive map
            * Shapefile loader
            * Database loader
    * Preliminary plan
        * This is a relatively large project with many parts. I would focus on getting a minimal subset of the parts working and iterate from there. If you are having trouble integrating one part with the others, I would mock it (replace it with code that returns simulated data) and just make sure you get the application structure together. Prioritize documenting and testing your code.

**Comment by zackAemmer** [comment]
Hey Edward, I think this is the wrong feedback for our group, we are the OneBusAway (transit_vis) group 7

**Comment by elmisback** [comment]
Thanks for letting me know, sorry about the mixup! I edited the original comment with the actual feedback.

**Comment by zackAemmer** [comment]
Thank you!
